export const AUTH_START = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CATEGORIES_FETCHING = 'CATEGORIES_START_FETCHING';
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const CATEGORIES_FAIL = 'CATEGORIES_FAIL';

export const PRODUCTS_FETCHING = 'PRODUCTS_START_FETCHING';
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
